int input ADDER_INPUT_SIGN1;
bool input ADDER_INPUT_SIGN1_FAULT;
bool input ADDER_INPUT_SIGN1_CONNECTED;
int input ADDER_INPUT_SIGN2;
bool input ADDER_INPUT_SIGN2_FAULT;
bool input ADDER_INPUT_SIGN2_CONNECTED;
int input ADDER_INPUT_SIGN3;
bool input ADDER_INPUT_SIGN3_FAULT;
bool input ADDER_INPUT_SIGN3_CONNECTED;
int input ADDER_COEFFICIENT1;
int input ADDER_COEFFICIENT2;
int input ADDER_COEFFICIENT3;

int output ADDER_OUTPUT_SIGN;
int output ADDER_OUTPUT_SIGN_FAULT;

#START

ADDER_OUTPUT_SIGN = (ADDER_INPUT_SIGN1 * ADDER_COEFFICIENT1) +
                    (ADDER_INPUT_SIGN2 * ADDER_COEFFICIENT2) +
                    (ADDER_INPUT_SIGN3 * ADDER_COEFFICIENT3);

#END

