bool input BSWITCH_CONTROL_S;
bool input BSWITCH_CONTROL_S_FAULT;
bool input BSWITCH_CONTROL_S_CONNECTED;
int input BSWITCH_INP_SIGN_1;
bool input BSWITCH_INP_SIGN_1_FAULT;
bool input BSWITCH_INP_SIGN_1_CONNECTED;
int input BSWITCH_INP_SIGN_2;
bool input BSWITCH_INP_SIGN_2_FAULT;
bool input BSWITCH_INP_SIGN_2_CONNECTED;
bool input BSWITCH_CONTROL;

int output BSWITCH_OUTP_SIGN;
bool output BSWITCH_OUTP_SIGN_FAULT;

#START

bool switch = (BSWITCH_CONTROL_S_CONNECTED -> BSWITCH_CONTROL_S : BSWITCH_CONTROL);
BSWITCH_OUTP_SIGN = (switch -> BSWITCH_INP_SIGN_2 : BSWITCH_INP_SIGN_1);

#END

